---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-headless
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if eq .Values.keycloak.cache.type "ispn" }}
    - port: 7800
      targetPort: jgroups
      protocol: TCP
      name: jgroups
    - port: 57800
      targetPort: jgroups-fd
      protocol: TCP
      name: jgroups-fd
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}